server:
  port: 8082
spring:
  application:
    name: nacos-cousmer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  okhttp:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
        execution:
          timeout:
            enable: false


